local CLOTHING = {}

CLOTHING.outfit_anorak_loner1 = {}
CLOTHING.outfit_anorak_loner2 = {}
CLOTHING.outfit_anorak_loner3 = {}
CLOTHING.outfit_anorak_loner4 = {}
CLOTHING.outfit_anorak_loner5 = {}
CLOTHING.outfit_anorak_loner6 = {}
CLOTHING.outfit_anorak_loner7 = {}
CLOTHING.outfit_anorak_loner8 = {}
CLOTHING.outfit_anorak_loner9 = {}
CLOTHING.outfit_anorak_loner10 = {}
CLOTHING.outfit_anorak_loner11 = {}
CLOTHING.outfit_anorak_loner12 = {}
CLOTHING.outfit_anorak_loner13 = {}
CLOTHING.outfit_anorak_loner14 = {}
CLOTHING.outfit_anorak_loner15 = {}
CLOTHING.outfit_anorak_loner16 = {}
CLOTHING.outfit_anorak_loner17 = {}
CLOTHING.outfit_anorak_loner18 = {}
CLOTHING.outfit_anorak_loner19 = {}
CLOTHING.outfit_anorak_loner20 = {}
CLOTHING.outfit_anorak_loner21 = {}
CLOTHING.outfit_anorak_loner22 = {}
CLOTHING.outfit_anorak_loner23 = {}
CLOTHING.outfit_anorak_loner24 = {}
CLOTHING.outfit_anorak_loner25 = {}
CLOTHING.outfit_anorak_loner26 = {}
CLOTHING.outfit_anorak_loner27 = {}
CLOTHING.outfit_anorak_loner28 = {}
CLOTHING.outfit_anorak_loner29 = {}
CLOTHING.outfit_anorak_loner30 = {}
CLOTHING.outfit_anorak_loner31 = {}
CLOTHING.outfit_anorak_loner32 = {}
CLOTHING.outfit_anorak_loner33 = {}
CLOTHING.outfit_anorak_loner34 = {}
CLOTHING.outfit_anorak_loner35 = {}
CLOTHING.outfit_anorak_bandit1 = {}
CLOTHING.outfit_anorak_bandit2 = {}
CLOTHING.outfit_anorak_bandit3 = {}
CLOTHING.outfit_anorak_bandit4 = {}
CLOTHING.outfit_anorak_bandit5 = {}
CLOTHING.outfit_anorak_bandit6 = {}
CLOTHING.outfit_anorak_bandit7 = {}
CLOTHING.outfit_anorak_bandit8 = {}
CLOTHING.outfit_anorak_bandit9 = {}
CLOTHING.outfit_anorak_bandit10 = {}
CLOTHING.outfit_anorak_bandit11 = {}
CLOTHING.outfit_anorak_bandit12 = {}
CLOTHING.outfit_anorak_clearsky1 = {}
CLOTHING.outfit_anorak_duty1 = {}
CLOTHING.outfit_anorak_duty2 = {}
CLOTHING.outfit_anorak_duty3 = {}
CLOTHING.outfit_anorak_freedom1 = {}
CLOTHING.outfit_anorak_freedom2 = {}
CLOTHING.outfit_anorak_freedom3 = {}
CLOTHING.outfit_anorak_freedom4 = {}
CLOTHING.outfit_anorak_merc1 = {}
CLOTHING.outfit_anorak_merc2 = {}
CLOTHING.outfit_anorak_merc3 = {}
CLOTHING.outfit_anorak_merc4 = {}
CLOTHING.outfit_anorak_military1 = {}
CLOTHING.outfit_anorak_military2 = {}
CLOTHING.outfit_anorak_unique = {}

-- DO NOT TOUCH BELOW IT ADDS THE ITEMS TO THE SCHEMA
for k, v in pairs(CLOTHING) do
	UNIQUE_ID = "outfit_" .. k
	local ITEM = ix.item.Register(UNIQUE_ID, "base_bmclothing", false, nil, true)
	ITEM.name = v.name or k
	ITEM.model = v.model or "models/props_junk/cardboard_box004a.mdl"
	ITEM.description = v.description or "This does not provide sufficient protection from the Zone's harsh conditions."
	ITEM.category = "Clothing"
	ITEM.ap = v.ap or 0
	ITEM.price = v.price or 100000000
	ITEM.weight = v.weight or 100000000
	ITEM.width = v.width or 1
	ITEM.height = v.height or 1
	ITEM.bmSlot = "torso"
	ITEM.bmModel = v.bmModel
	ITEM.bmSkin = v.bmSkin or 0
end