local CLOTHING = {}

CLOTHING.outfit_sunrise_loner1 = {}
CLOTHING.outfit_sunrise_loner2 = {}
CLOTHING.outfit_sunrise_loner3 = {}
CLOTHING.outfit_sunrise_loner4 = {}
CLOTHING.outfit_sunrise_loner5 = {}
CLOTHING.outfit_sunrise_loner6 = {}
CLOTHING.outfit_sunrise_loner7 = {}
CLOTHING.outfit_sunrise_loner8 = {}
CLOTHING.outfit_sunrise_loner9 = {}
CLOTHING.outfit_sunrise_loner10 = {}
CLOTHING.outfit_sunrise_loner11 = {}
CLOTHING.outfit_sunrise_loner12 = {}
CLOTHING.outfit_sunrise_loner13 = {}
CLOTHING.outfit_sunrise_loner14 = {}
CLOTHING.outfit_sunrise_loner15 = {}
CLOTHING.outfit_sunrise_loner16 = {}
CLOTHING.outfit_sunrise_loner17 = {}
CLOTHING.outfit_sunrise_loner18 = {}
CLOTHING.outfit_sunrise_loner19 = {}
CLOTHING.outfit_sunrise_loner20 = {}
CLOTHING.outfit_sunrise_loner21 = {}
CLOTHING.outfit_sunrise_loner22 = {}
CLOTHING.outfit_sunrise_merc1 = {}
CLOTHING.outfit_sunrise_military1 = {}
CLOTHING.outfit_sunrise_monolith1 = {}
CLOTHING.outfit_nbc_bandit = {}
CLOTHING.outfit_nbc_duty1 = {}
CLOTHING.outfit_nbc_freedom1 = {}
CLOTHING.outfit_nbc_loner1 = {}
CLOTHING.outfit_nbc_loner2 = {}
CLOTHING.outfit_nbc_monolith1 = {}
CLOTHING.outfit_ps5_bandit1 = {}
CLOTHING.outfit_ps5_bandit2 = {}
CLOTHING.outfit_ps5_beyond1 = {}
CLOTHING.outfit_ps5_clearsky1 = {}
CLOTHING.outfit_ps5_clearsky2 = {}
CLOTHING.outfit_ps5_duty1 = {}
CLOTHING.outfit_ps5_duty2 = {}
CLOTHING.outfit_ps5_finalday1 = {}
CLOTHING.outfit_ps5_freedom1 = {}
CLOTHING.outfit_ps5_freedom2 = {}
CLOTHING.outfit_ps5_freedom3 = {}
CLOTHING.outfit_ps5_freedom4 = {}
CLOTHING.outfit_ps5_isg1 = {}
CLOTHING.outfit_ps5_merc1 = {}
CLOTHING.outfit_ps5_merc2 = {}
CLOTHING.outfit_ps5_monolith1 = {}
CLOTHING.outfit_ps5_monolith2 = {}
CLOTHING.outfit_ps5_monolith3 = {}
CLOTHING.outfit_psz9_loner1 = {}
CLOTHING.outfit_psz9_loner2 = {}
CLOTHING.outfit_psz9_loner3 = {}
CLOTHING.outfit_psz9_loner4 = {}
CLOTHING.outfit_psz9_loner5 = {}
CLOTHING.outfit_psz9_bandit1 = {}
CLOTHING.outfit_psz9_bandit2 = {}
CLOTHING.outfit_psz9_clearsky1 = {}
CLOTHING.outfit_psz9_duty1 = {}
CLOTHING.outfit_psz9_duty2 = {}
CLOTHING.outfit_psz9_duty3 = {}
CLOTHING.outfit_psz9_duty4 = {}
CLOTHING.outfit_psz9_ecologist1 = {}
CLOTHING.outfit_psz9_ecologist2 = {}
CLOTHING.outfit_psz9_ecologist3 = {}
CLOTHING.outfit_psz9_ecologist4 = {}
CLOTHING.outfit_psz9_freedom1 = {}
CLOTHING.outfit_psz9_freedom2 = {}
CLOTHING.outfit_psz9_freedom3 = {}
CLOTHING.outfit_psz9_freedom4 = {}
CLOTHING.outfit_psz9_freedom5 = {}
CLOTHING.outfit_psz9_freedom6 = {}
CLOTHING.outfit_psz9_freedom7 = {}
CLOTHING.outfit_psz9_isg1 = {}
CLOTHING.outfit_psz9_military1 = {}
CLOTHING.outfit_psz9_military2 = {}
CLOTHING.outfit_psz9_monolith1 = {}
CLOTHING.outfit_psz9_sin1 = {}
CLOTHING.outfit_psz9_sin2 = {}
CLOTHING.outfit_psz9_sin3 = {}
CLOTHING.outfit_seva_loner1 = {}
CLOTHING.outfit_seva_loner2 = {}
CLOTHING.outfit_seva_loner3 = {}
CLOTHING.outfit_seva_loner4 = {}
CLOTHING.outfit_seva_loner5 = {}	
CLOTHING.outfit_seva_bandit1 = {}
CLOTHING.outfit_seva_bandit2 = {}
CLOTHING.outfit_seva_clearsky1 = {}
CLOTHING.outfit_seva_clearsky2 = {}
CLOTHING.outfit_seva_clearsky3 = {}
CLOTHING.outfit_seva_duty1 = {}
CLOTHING.outfit_seva_duty2 = {}
CLOTHING.outfit_seva_duty3 = {}
CLOTHING.outfit_seva_duty4 = {}
CLOTHING.outfit_seva_ecologist1 = {}
CLOTHING.outfit_seva_freedom1 = {}
CLOTHING.outfit_seva_freedom2 = {}
CLOTHING.outfit_seva_freedom3 = {}
CLOTHING.outfit_seva_isg1 = {}
CLOTHING.outfit_seva_isg2 = {}
CLOTHING.outfit_seva_isg3 = {}
CLOTHING.outfit_seva_merc1 = {}
CLOTHING.outfit_seva_merc2 = {}
CLOTHING.outfit_seva_merc3 = {}
CLOTHING.outfit_seva_merc4 = {}
CLOTHING.outfit_seva_merc5 = {}
CLOTHING.outfit_seva_merc6 = {}
CLOTHING.outfit_seva_military1 = {}
CLOTHING.outfit_seva_military2 = {}
CLOTHING.outfit_seva_monolith1 = {}

-- DO NOT TOUCH BELOW IT ADDS THE ITEMS TO THE SCHEMA
for k, v in pairs(CLOTHING) do
	UNIQUE_ID = "outfit_" .. k
	local ITEM = ix.item.Register(UNIQUE_ID, "base_bmclothing", false, nil, true)
	ITEM.name = v.name or k
	ITEM.model = v.model or "models/props_junk/cardboard_box004a.mdl"
	ITEM.description = v.description or "This does not provide sufficient protection from the Zone's harsh conditions."
	ITEM.category = "Clothing"
	ITEM.ap = v.ap or 0
	ITEM.price = v.price or 100000000
	ITEM.weight = v.weight or 100000000
	ITEM.width = v.width or 1
	ITEM.height = v.height or 1
	ITEM.bmSlot = "torso"
	ITEM.bmModel = v.bmModel
	ITEM.bmSkin = v.bmSkin or 0
end